# Generated by Django 4.2.5 on 2023-09-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transit", "0004_transit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="transit",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="transit.location",
            ),
        ),
        migrations.AddField(
            model_name="transit",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="transit",
            name="transit_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="transit.location",
            ),
        ),
    ]
