# Generated by Django 4.2.5 on 2023-09-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transit", "0005_delete_driver_location_latitude_location_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=51.5406, max_digits=9),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="transit",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="transit.location",
            ),
        ),
        migrations.AlterField(
            model_name="transit",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="transit",
            name="transit_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="transit.location",
            ),
        ),
    ]
