# Generated by Django 4.2.5 on 2023-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transit", "0006_alter_location_latitude_alter_location_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
