# Generated by Django 4.2.2 on 2023-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_alter_location_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
