# Generated by Django 4.2.2 on 2023-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0010_driver_remove_user_driver_remove_user_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
