# Generated by Django 4.2.2 on 2023-09-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0014_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accessibility',
            field=models.TextField(default='Nil'),
        ),
    ]
